function loadXmlFiles(){importXML('','files/xml/testTips.xml',true,true);}
function importXML(selectIndex,url,topicsOnly,initLoad){var reqHttp_request='';if(window.XMLHttpRequest){try{reqHttp_request=new XMLHttpRequest();}catch(e){reqHttp_request=false;alert('Cannot create XMLHttpRequest\n'+ e);}
try{if(reqHttp_request){reqHttp_request.onreadystatechange=function(){if(reqHttp_request.readyState==4){if(topicsOnly){switch(url){case'files/xml/testTips.xml':clearBox('tips');loadXmlTopics(reqHttp_request.responseXML,'tips','tip','category','category',true);if(initLoad){importXML('','files/xml/checklist.xml',true,true);}
break;case'files/xml/checklist.xml':clearBox('checkItems');loadXmlTopics(reqHttp_request.responseXML,'checkItems','item','name','name',true);if(initLoad){importXML('','files/xml/encodings.xml',true,true);}
break;case'files/xml/encodings.xml':clearBox('encodingType');loadXmlTopics(reqHttp_request.responseXML,'encodingType','type','display','value',true);clearBox('decodingType');loadXmlTopics(reqHttp_request.responseXML,'decodingType','type','display','value',true);if(initLoad){importXML('','files/xml/reqRespHistory.xml',true,true,true);}
break;case'files/xml/reqRespHistory.xml':clearBox('reqHistory');loadXmlTopics(reqHttp_request.responseXML,'reqHistory','case','time','time',true);clearBox('resHistory');loadXmlTopics(reqHttp_request.responseXML,'resHistory','case','time','time',true);if(initLoad){importXML('','files/xml/automator.xml',true,true,true);}
break;case'files/xml/automator.xml':clearBox('lists');loadXmlTopics(reqHttp_request.responseXML,'lists','list','listName','listName',true);clearBox('reqLists');loadXmlTopics(reqHttp_request.responseXML,'reqLists','list','listName','listName',true);if(initLoad){importXML('','files/xml/xssAttacks.xml',true,true);}
break;case'files/xml/xssAttacks.xml':clearBox('xssType');if(initLoad){loadXmlTopics(reqHttp_request.responseXML,'xssType','attack','name','name',true);importXML('','files/xml/xssUserAttacks.xml',true,true);}else{loadXmlTopics(reqHttp_request.responseXML,'xssType','attack','name','name',false);importXML('','files/xml/xssUserAttacks.xml',true,false);goToAnchor('#xssAttacks');}
break;case'files/xml/xssUserAttacks.xml':if(initLoad){loadXmlTopics(reqHttp_request.responseXML,'xssType','attack','name','name',true);}else{loadXmlTopics(reqHttp_request.responseXML,'xssType','attack','name','name',false);goToAnchor('#xssAttacks');}
break;default:displayMessage('Topic loading Error');}}else{loadDetails(selectIndex,reqHttp_request.responseXML,url);}}}
reqHttp_request.open("GET",url,true);reqHttp_request.send(null);}else{displayMessage('XMLHttpRequest Retrieval Error');}}catch(e){alert('ERROR:\n'+ e);}}else if(window.ActiveXObject){var xmlDoc=new ActiveXObject("Microsoft.XMLDOM");xmlDoc.async="false";xmlDoc.load(url);if(xmlDoc.readyState==4){if(topicsOnly){switch(url){case'files/xml/testTips.xml':clearBox('tips');loadXmlTopics(xmlDoc,'tips','tip','category','category',true);if(initLoad){importXML('','files/xml/checklist.xml',true,true);}
break;case'files/xml/checklist.xml':clearBox('checkItems');loadXmlTopics(xmlDoc,'checkItems','item','name','name',true);if(initLoad){importXML('','files/xml/encodings.xml',true,true);}
break;case'files/xml/encodings.xml':clearBox('encodingType');loadXmlTopics(xmlDoc,'encodingType','type','display','value',true);clearBox('decodingType');loadXmlTopics(xmlDoc,'decodingType','type','display','value',true);if(initLoad){importXML('','files/xml/reqRespHistory.xml',true,true);}
break;case'files/xml/reqRespHistory.xml':clearBox('reqHistory');loadXmlTopics(xmlDoc,'reqHistory','case','time','time',true);clearBox('resHistory');loadXmlTopics(xmlDoc,'resHistory','case','time','time',true);if(initLoad){importXML('','files/xml/automator.xml',true,true);}
break;case'files/xml/automator.xml':clearBox('lists');loadXmlTopics(xmlDoc,'lists','list','listName','listName',true);clearBox('reqLists');loadXmlTopics(xmlDoc,'reqLists','list','listName','listName',true);if(initLoad){importXML('','files/xml/xssAttacks.xml',true,true);}
break;case'files/xml/xssAttacks.xml':clearBox('xssType');if(initLoad){loadXmlTopics(xmlDoc,'xssType','attack','name','name',true);importXML('','files/xml/xssUserAttacks.xml',true,true);}else{loadXmlTopics(xmlDoc,'xssType','attack','name','name',false);importXML('','files/xml/xssUserAttacks.xml',true,false);goToAnchor('#xssAttacks');}
break;case'files/xml/xssUserAttacks.xml':if(initLoad){loadXmlTopics(xmlDoc,'xssType','attack','name','name',true);}else{loadXmlTopics(xmlDoc,'xssType','attack','name','name',false);goToAnchor('#xssAttacks');}
break;default:displayMessage('Topic loading Error');}}else{loadDetails(selectIndex,xmlDoc,url);}}}}
function loadXmlTopics(xmlDoc,selectID,xmlNode,textName,valName,showAll){var x=new Array();var xLen=0;var label=' ';var newOptgroup='';var newOpt='';var browNode='';var sel=document.getElementById(selectID);var attr=selectID.substring(0,2);if(selectID=='xssType'){document.getElementById('browser').innerHTML='Browser support:&nbsp;';document.getElementById('xssTitle').innerHTML='Description:';}
if(xmlDoc){x=xmlDoc.getElementsByTagName(xmlNode);xLen=x.length;var browVal=document.getElementById('browFilter').value;for(var i=0;i<xLen;i++){if(x[i].hasChildNodes()){if(typeof x[i].getElementsByTagName('browser')[0]!=typeof undefined){if(x[i].getElementsByTagName('browser').length>0){browNode=getText(x[i].getElementsByTagName('browser')[0]);}else{browNode='';}}else{browNode='';}
if(showAll){if((selectID!='reqHistory')&&(selectID!='resHistory')&&(selectID!='lists')&&(selectID!='reqLists')){if(label!=getText(x[i].getElementsByTagName('label')[0])){newOptgroup=document.createElement('optgroup');newOptgroup.label=getText(x[i].getElementsByTagName('label')[0]);newOptgroup.id=attr+ i;sel.appendChild(newOptgroup);label=getText(x[i].getElementsByTagName('label')[0]);}}
newOpt=document.createElement('option');newOpt.text=getText(x[i].getElementsByTagName(textName)[0]);newOpt.value=getText(x[i].getElementsByTagName(valName)[0]);try{if((selectID!='reqHistory')&&(selectID!='resHistory')&&(selectID!='lists')&&(selectID!='reqLists')){sel.add(newOpt);}else{document.getElementById(selectID).add(newOpt);}}catch(ex){if((selectID!='reqHistory')&&(selectID!='resHistory')&&(selectID!='lists')&&(selectID!='reqLists')){newOptgroup.appendChild(newOpt);}else{document.getElementById(selectID).appendChild(newOpt);}}}else if(browserType(browNode,browVal)){clearXSSField('xssClearAll');if(label!=getText(x[i].getElementsByTagName('label')[0])){newOptgroup=document.createElement('optgroup');newOptgroup.label=getText(x[i].getElementsByTagName('label')[0]);newOptgroup.id=attr+ i;sel.appendChild(newOptgroup);label=getText(x[i].getElementsByTagName('label')[0]);}
newOpt=document.createElement('option');newOpt.text=getText(x[i].getElementsByTagName(textName)[0]);newOpt.value=getText(x[i].getElementsByTagName(valName)[0]);try{if((selectID!='reqHistory')&&(selectID!='resHistory')&&(selectID!='lists')&&(selectID!='reqLists')){sel.add(newOpt);}else{document.getElementById(selectID).add(newOpt);}}catch(ex){if((selectID!='reqHistory')&&(selectID!='resHistory')&&(selectID!='lists')&&(selectID!='reqLists')){newOptgroup.appendChild(newOpt);}else{document.getElementById(selectID).appendChild(newOpt);}}}}}}}
function browserType(browserNode,browserFilter){var browSplit='';var browSplitLen=0;var ebsLen=editBrowString.length;if(browserNode!=''){browSplit=browserNode.split(',');browSplitLen=browSplit.length;}
switch(browserFilter){case'':return true;break;case'ALL':for(var a=0;a<ebsLen;a++){if(editBrowString[a]!=browSplit[a]){return false;}}
return true;break;default:for(var a=0;a<browSplitLen;a++){if(browSplit[a]==browserFilter){return true;}}
return false;}}
function browserDisplay(browList){var browSplit='';var browOut='';var match=false;if(browList!=''){browSplit=browList.split(',');}
if(browSplit.length>0){for(var a=0;a<editBrowString.length;a++){for(var b=0;b<browSplit.length;b++){if(editBrowString[a]==browSplit[b]){browOut+='[<span class="s">'+ browSplit[b]+'</span>]';match=true;}}
if(!match){browOut+='[<span class="ns">'+ editBrowString[a]+'</span>]';}
match=false;}}
return browOut;}
var reqFieldArray=new Array('reqMethod','reqSchema','reqFqdn','reqPort','reqPath','reqSeparator','reqParameter','reqQSep','reqQString','reqHead','reqBody','reqAuth','reqUser','reqPass','reqUpFile','resTargetUrl','resStatCode','resStatText','resHead','resBody');var reqNodeArray=new Array('method','schema','uri','port','path','paramSep','parameter','querySep','queryString','headers','values','authType','authUser','authPass','file','resTargetUrl','resStatCode','resStatText','resHead','resBody');function loadDetails(pointer,xmlDoc,url){if(url=='files/xml/xssAttacks.xml'){var xLoad=new Array();xLoad=xmlDoc.getElementsByTagName('attack');var xXmlLen=xLoad.length;clearXSSField('xssClearAll');for(var i=0;i<xXmlLen;i++){if(xLoad[i].hasChildNodes()){if(getText(xLoad[i].getElementsByTagName('name')[0])==pointer){document.XSS.attackCode.value=getText(xLoad[i].getElementsByTagName('code')[0]);document.XSS.description.value=getText(xLoad[i].getElementsByTagName('desc')[0]);document.getElementById('browser').innerHTML='Browser support:&nbsp;'+
browserDisplay(getText(xLoad[i].getElementsByTagName('browser')[0]));document.getElementById('xssTitle').innerHTML='Description:';return;}}}
importXML(pointer,'files/xml/xssUserAttacks.xml',false);}else if(url=='files/xml/xssUserAttacks.xml'){var x=new Array();x=xmlDoc.getElementsByTagName('attack');var uaXmlLen=x.length;for(var i=0;i<uaXmlLen;i++){if(x[i].hasChildNodes()){if(getText(x[i].getElementsByTagName('name')[0])==pointer){document.XSS.udAttackTitle.value=getText(x[i].getElementsByTagName('name')[0]);document.XSS.attackCode.value=getText(x[i].getElementsByTagName('code')[0]);document.XSS.description.value=getText(x[i].getElementsByTagName('desc')[0]);document.getElementById('browser').innerHTML='Browser support:&nbsp;'+
browserDisplay(getText(x[i].getElementsByTagName('browser')[0]));document.getElementById('xssTitle').innerHTML='Description:';if(typeof x[i].getElementsByTagName('browser')[0]!=typeof undefined){browNode=getText(x[i].getElementsByTagName('browser')[0]);}else{browNode=' ';}
for(var j=0;j<editBrowString.length;j++){if(browserType(browNode,editBrowString[j])){document.getElementById('ud'+ editBrowString[j]).checked=true;}else{document.getElementById('ud'+ editBrowString[j]).checked=false;}}
return;}}else{displayMessage('XSS Attack Information Not Found');}}}else if(url=='files/xml/testTips.xml'){var xTip=new Array();xTip=xmlDoc.getElementsByTagName('tip');var xTipLen=xTip.length;var chIndex=document.getElementById('tips').selectedIndex;if((chIndex>=0)&&(chIndex<=xTipLen)){document.CHECKLIST.desc.value=getText(xTip[chIndex].getElementsByTagName('desc')[0]);document.CHECKLIST.examples.value=getText(xTip[chIndex].getElementsByTagName('examples')[0]);return;}else{displayMessage('Testing Tip Not Found');return;}}else if(url=='files/xml/checklist.xml'){var xChk=new Array();xChk=xmlDoc.getElementsByTagName('item');var xChkLen=xChk.length;for(var i=0;i<xChkLen;i++){if(xChk[i].hasChildNodes()){if(getText(xChk[i].getElementsByTagName('name')[0])==pointer){document.CHECKLIST.checkTitle.value=getText(xChk[i].getElementsByTagName('name')[0]);document.CHECKLIST.checkResults.value=getText(xChk[i].getElementsByTagName('results')[0]);document.CHECKLIST.checkLabel.value=getText(xChk[i].getElementsByTagName('label')[0]);return;}}else{displayMessage('Checklist Item Not Found');return;}}}else if(url=='files/xml/reqRespHistory.xml'){var xHist=new Array();xHist=xmlDoc.getElementsByTagName('case');var xHistLen=xHist.length;var reqFieldLen=reqFieldArray.length;for(var i=0;i<xHistLen;i++){if(xHist[i].hasChildNodes()){if(getText(xHist[i].getElementsByTagName('time')[0])==pointer){for(var j=0;j<reqFieldLen;j++){document.getElementById(reqFieldArray[j]).value=cdataDecode(getText(xHist[i].getElementsByTagName(reqNodeArray[j])[0]));if(document.getElementById(reqFieldArray[j]).value==' '){document.getElementById(reqFieldArray[j]).value='';}}
return;}}else{displayMessage('Request/Response Not Found');return;}}}else{displayMessage('No File To Load');return;}}
function cdataDecode(inSource){var cdataReg=new RegExp('\&\#93\;','g');var encSource='';if(inSource!=''){encSource=inSource.replace(cdataReg,']');return(encSource);}else{return(inSource);}}
function getText(inElement){if(typeof inElement.textContent!=typeof undefined){return inElement.textContent;}else if(typeof inElement.firstChild!=typeof undefined){return inElement.firstChild.nodeValue;}else{return null;}}
function clearBox(boxID){var selID='';if(boxID!=''){selID=document.getElementById(boxID);}
if(selID){while(selID.firstChild){selID.removeChild(selID.firstChild);}}}