function saveData(folder,nameSuffix,extension,inContent){var content='';var contentEnc='';if(nameSuffix=='State'){content=getStateContent();}else{content=inContent;}
contentEnc=content.toString();var dcLen=contentEnc.length;for(var k=0;k<dcLen;k++){if(contentEnc.charCodeAt(k)>255){if((nameSuffix=='State')||(nameSuffix=='responseBody')){contentEnc=contentEnc.replace(contentEnc.charAt(k),plainToUnicode(contentEnc.charAt(k),'unicode',false,'','')+'!@');}else{contentEnc=contentEnc.replace(contentEnc.charAt(k),plainToDecimal(contentEnc.charAt(k),'entityDec','',';'));}
dcLen=contentEnc.length;}}
var backupPath=getBackupPath(folder,nameSuffix,extension);var backup=saveFile(backupPath,contentEnc);if(backupPath&&backup){displayMessage('Save Successful');}else{displayMessage('Save Not Successful');}}
function getStateContent(){var input=new Array();var textarea=new Array();input=document.getElementsByTagName('input');textarea=document.getElementsByTagName('textarea');var strippedText=new Array();var strippedArea=new Array();var data=new Array();var inLength=input.length;for(var i=0;i<inLength;i++){if(input[i].type=='text'){strippedText.push(input[i]);}}
input=strippedText;var texLength=textarea.length;for(var i=0;i<texLength;i++){if(textarea[i].getAttribute('id').substr(0,4)=='code'){}else{strippedArea.push(textarea[i]);}}
textarea=strippedArea;inLength=input.length;if(inLength>0){for(var i=0;i<inLength;i++){data.push(input[i].value.toString()+'+*-');}}
texLength=textarea.length;for(var j=0;j<texLength;j++){if(j==(texLength- 1)){data.push(textarea[j].value.toString());}else{data.push(textarea[j].value.toString()+'+*-');}}
return(data);}
function getBackupPath(backupFolder,nameSuffix,extension){var pagePath='';var hashPos='';var systemPath='';var backupPath='';var regexSlash=new RegExp("/","g");var dirPathLoc='';var backSlash=true;pagePath=document.location.toString();hashPos=pagePath.indexOf("#");if(hashPos!=-1){pagePath=pagePath.substring(0,hashPos);}
if(pagePath.charAt(9)==":"){systemPath=unescape(pagePath.substr(8)).replace(regexSlash,"\\");}else if(pagePath.substr(0,17)=="file://localhost/"){systemPath=unescape(pagePath.substr(16));}else if(pagePath.substr(0,8)=="file:///"){systemPath=unescape(pagePath.substr(7));}else if(pagePath.substr(0,7)=="file://"){systemPath=unescape(pagePath.substr(6));}else if(pagePath.substr(0,5)=="file:/"){systemPath=unescape(pagePath.substr(5));}else{systemPath="\\\\"+ unescape(pagePath.substr(7)).replace(regexSlash,"\\");}
dirPathLoc=systemPath.lastIndexOf("\\");if(dirPathLoc==-1){dirPathLoc=systemPath.lastIndexOf("/");backSlash=false;}
backupPath=systemPath.substr(0,dirPathLoc)+"/"+ backupFolder+"/"+ nameSuffix+"."+ extension;if(backSlash){backupPath=backupPath.replace(regexSlash,"\\");}
return backupPath;}
function saveFile(fileUrl,content){var fileSave=false;fileSave=mozillaSaveFile(fileUrl,content);if(fileSave==false){fileSave=ieSaveFile(fileUrl,content);}
if(fileSave){return(fileSave);}else{displayMessage('Error trying to save file');return(false);}}
function mozillaSaveFile(filePath,content){var mozSave='';var moz='';if(window.Components){try{netscape.security.PrivilegeManager.enablePrivilege("UniversalXPConnect");mozSave=Components.classes["@mozilla.org/file/local;1"].createInstance(Components.interfaces.nsILocalFile);mozSave.initWithPath(filePath);if(!mozSave.exists()){mozSave.create(0,0664);}
moz=Components.classes["@mozilla.org/network/file-output-stream;1"].createInstance(Components.interfaces.nsIFileOutputStream);moz.init(mozSave,0x20|0x02,00004,null);moz.write(content,content.toString().length);moz.flush();moz.close();return(true);}catch(e){alert("Error while attempting to save\n"+ e.toString());return(false);}}else{return(false);}}
function ieSaveFile(filePath,content){var ieSave='';var ie='';try{if(typeof window.ActiveXObject!=typeof undefined){ieSave=new ActiveXObject("Scripting.FileSystemObject");}else{return(false);}}catch(e){alert("Error while attempting to save\n"+ e.toString());return(false);}
if(ieSave){ie=ieSave.OpenTextFile(filePath,2,-1,0);ie.Write(content);ie.Close();return(true);}else{return(false);}}
function loadData(folder,nameSuffix,extension){var fileLoad=false;var filePath=getBackupPath(folder,nameSuffix,extension);var unReg=/\%\u(.){4}\!\@/gi;var regMatch=new Array();var regReplace='';var info=new Array();fileLoad=mozillaLoadFile(filePath);if(fileLoad==false){fileLoad=ieLoadFile(filePath);}
if(fileLoad!=''){regMatch=fileLoad.match(unReg);if(regMatch){var regLen=regMatch.length;if(regLen>0){for(var x=0;x<regLen;x++){regReplace=regMatch[x].replace('!@','');regReplace=unescape(regReplace);fileLoad=fileLoad.replace(regMatch[x],regReplace);}}}
if(nameSuffix=='State'){var input=document.getElementsByTagName('input');var textarea=document.getElementsByTagName('textarea');clearResField('resElements',false,true);info=fileLoad.split('+*-,');var inLength=input.length;for(var i=0;i<inLength;i++){if(input[i].type=='text'){input[i].value=info.shift();}}
var texLen=textarea.length;for(var j=0;j<texLen;j++){if(textarea[j].getAttribute('id').substr(0,4)=='code'){}else{textarea[j].value=info.shift();}}
displayMessage('Backup Retrieved');return'';}else{return fileLoad;}}else{displayMessage('No File To Load');return'';}}
function mozillaLoadFile(filePath){var file='';var inputStream='';var mozInputStream='';if(window.Components){try{netscape.security.PrivilegeManager.enablePrivilege("UniversalXPConnect");file=Components.classes["@mozilla.org/file/local;1"].createInstance(Components.interfaces.nsILocalFile);file.initWithPath(filePath);if(!file.exists()){return(false);}
inputStream=Components.classes["@mozilla.org/network/file-input-stream;1"].createInstance(Components.interfaces.nsIFileInputStream);inputStream.init(file,0x01,00004,null);mozInputStream=Components.classes["@mozilla.org/scriptableinputstream;1"].createInstance(Components.interfaces.nsIScriptableInputStream);mozInputStream.init(inputStream);return(mozInputStream.read(mozInputStream.available()));}catch(e){alert("Error while attempting to load\n"+ e.toString());return(false);}}else{return(false);}}
function ieLoadFile(filePath){var ieLoad='';var file='';var content='';try{if(typeof window.ActiveXObject!=typeof undefined){ieLoad=new ActiveXObject("Scripting.FileSystemObject");}else{return(false);}
file=ieLoad.OpenTextFile(filePath,1);content=file.ReadAll();file.Close();return(content);}catch(e){alert("Error while attempting to load\n"+ e.toString());return(false);}}